import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Flatten



x_test = np.load('DATA/Original/x_test.npy')
y_test = np.load('DATA/Original/y_test.npy')
x_train = np.load('DATA/Original/x_train.npy')
y_train = np.load('DATA/Original/y_train.npy')
model = Sequential()
model.add(Conv2D(16, (3,3), activation='relu', input_shape=(256,256,3)))
model.add(Conv2D(16, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(9, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=50, epochs=200, verbose=1, validation_split=0.2)    
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)


x_train = np.load('DATA/Generic/x_train.npy')
y_train = np.load('DATA/Generic/y_train.npy')
model = Sequential()
model.add(Conv2D(16, (3,3), activation='relu', input_shape=(256,256,3)))
model.add(Conv2D(16, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(9, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=50, epochs=200, verbose=1, validation_split=0.2)    
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)


x_train = np.load('DATA/Our_method/x_train.npy')
y_train = np.load('DATA/Our_method/y_train.npy')  
model = Sequential()
model.add(Conv2D(16, (3,3), activation='relu', input_shape=(256,256,3)))
model.add(Conv2D(16, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(Conv2D(32, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(Conv2D(64, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(Conv2D(128, (3,3), activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(9, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=50, epochs=200, verbose=1, validation_split=0.2)    
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)